# Generated by Django 4.0.2 on 2022-03-02 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_comment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='date_time',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
    ]
