# Generated by Django 4.0.2 on 2022-02-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_mediafiles_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafiles',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='post',
            name='friend',
        ),
    ]
