# Generated by Django 4.0.2 on 2022-02-21 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_mediafiles_friend_remove_post_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='post.post'),
        ),
    ]
