# Generated by Django 4.0.2 on 2022-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
