# Generated by Django 4.0.2 on 2022-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_image_alter_mediafiles_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
