# Generated by Django 4.0.2 on 2022-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_mediafiles_images_alter_mediafiles_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
