# Generated by Django 4.0.2 on 2022-02-23 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_mediafiles_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='date_time',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
    ]
