# Generated by Django 4.0.2 on 2022-02-23 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_comment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='date_time',
            field=models.DateField(default=datetime.date(2022, 2, 23)),
        ),
    ]
