# Generated by Django 4.0.2 on 2022-02-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageImage',
            field=models.ImageField(default=1, upload_to='mypage/'),
            preserve_default=False,
        ),
    ]
