# Generated by Django 4.0.2 on 2022-02-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageImage',
            field=models.ImageField(blank=True, null=True, upload_to='mypage/'),
        ),
    ]
