# Generated by Django 4.0.2 on 2022-02-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_pagemedia_page_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemedia',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
            preserve_default=False,
        ),
    ]
