# Generated by Django 4.0.2 on 2022-02-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_pagemedia_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
    ]
