# Generated by Django 4.0.2 on 2022-02-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelikes',
            name='admin',
        ),
    ]
