# Generated by Django 4.0.2 on 2022-03-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_pagemedia_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemedia',
            name='Page_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostMedia', to='page.pagepost'),
        ),
    ]
